# Generated by Django 3.1.5 on 2021-09-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComEventList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=50)),
                ('eventdate', models.CharField(max_length=50)),
                ('predtime', models.FloatField(max_length=50)),
                ('emerge', models.CharField(max_length=50)),
                ('costtime', models.FloatField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=50)),
                ('eventdate', models.CharField(max_length=50)),
                ('predtime', models.FloatField(max_length=50)),
                ('emerge', models.CharField(max_length=50)),
            ],
        ),
    ]
