# Generated by Django 3.1.5 on 2021-09-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comeventlist',
            name='costtime',
            field=models.FloatField(max_length=50, verbose_name='costtime'),
        ),
        migrations.AlterField(
            model_name='comeventlist',
            name='emerge',
            field=models.CharField(max_length=50, verbose_name='emerge'),
        ),
        migrations.AlterField(
            model_name='comeventlist',
            name='eventdate',
            field=models.CharField(max_length=50, verbose_name='eventdate'),
        ),
        migrations.AlterField(
            model_name='comeventlist',
            name='eventname',
            field=models.CharField(max_length=50, verbose_name='eventname'),
        ),
        migrations.AlterField(
            model_name='comeventlist',
            name='predtime',
            field=models.FloatField(max_length=50, verbose_name='predtime'),
        ),
        migrations.AlterField(
            model_name='eventlist',
            name='emerge',
            field=models.CharField(max_length=50, verbose_name='emerge'),
        ),
        migrations.AlterField(
            model_name='eventlist',
            name='eventdate',
            field=models.CharField(max_length=50, verbose_name='eventdate'),
        ),
        migrations.AlterField(
            model_name='eventlist',
            name='eventname',
            field=models.CharField(max_length=50, verbose_name='eventname'),
        ),
        migrations.AlterField(
            model_name='eventlist',
            name='predtime',
            field=models.FloatField(max_length=50, verbose_name='predtime'),
        ),
    ]
